Repository swaraj961/loophole-bot, pull requests merged in 2023-10, with the labels that each got.

#6 Added Readme
  README.md
Labels: enhancement, help wanted, hacktoberfest

#7 removed lisense and refactor code
  LICENSE
  util/Util.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#8 Readme edits
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
